import = ["/home/mairacanal/.config/alacritty/colors.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 9

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 23

[window.padding]
x = 12
y = 12
