
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { style = "Bold" }
bold_italic = { style = "Bold Italic" }
italic = { style = "Italic" }
size = 9

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 23

[window.padding]
x = 12
y = 12

[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
